services:
  postgres:
    image: postgres:latest
    container_name: pulse-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: pulse
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: pulse_dev
    ports:
      - "5432:5432"
    volumes:
      - pulse-data:/var/lib/postgresql

volumes:
  pulse-data:
